# Generated by Django 4.1 on 2022-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_mon", "0002_auto_20220924_1516"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomaly",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="severity",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
